// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmcbOE_KP561uL6GEO0EAeiNKzu6bb4g',
    appId: '1:236562288830:web:ce3d770e4ac06a0c8b0eef',
    messagingSenderId: '236562288830',
    projectId: 'fitappv2',
    authDomain: 'fitappv2.firebaseapp.com',
    storageBucket: 'fitappv2.appspot.com',
    measurementId: 'G-FR9GKVPRY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzE11aE7kicqoqW1uXzbi_fxzYjj29uo',
    appId: '1:236562288830:android:c0df68b0caded1128b0eef',
    messagingSenderId: '236562288830',
    projectId: 'fitappv2',
    storageBucket: 'fitappv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDl9E_elDUjfumhBio8N6XgqvPhO8Eqsk',
    appId: '1:236562288830:ios:e6c5a34e694822b58b0eef',
    messagingSenderId: '236562288830',
    projectId: 'fitappv2',
    storageBucket: 'fitappv2.appspot.com',
    iosBundleId: 'com.example.fitappv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDl9E_elDUjfumhBio8N6XgqvPhO8Eqsk',
    appId: '1:236562288830:ios:eca981acd1cbe79d8b0eef',
    messagingSenderId: '236562288830',
    projectId: 'fitappv2',
    storageBucket: 'fitappv2.appspot.com',
    iosBundleId: 'com.example.fitappv2.RunnerTests',
  );
}
